name       : lia
version    : 1.0
release    : 2
source     :
    - https://github.com/himmAllRight/LIA/archive/1.1-beta.tar.gz : a0b3fa6798affd5eea1d6e5e4126f9a3fcdf6e136b4708f284ab78ac0d715021
license    : GPL-3.0 # CHECK ME
component  : office
summary    : A command line tool to easily import/convert bank and credit card statments to a ledger file.
description: |
  LIA is a simple command-line python application that can help import exported Cedit Card and Bank statement csv files into a ledger journal file
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - ledger
install    : |
    %python3_install
